name: Bug Report
description: 'This form is for a issue you are experiencing with the modpack. '
title: '[Bug]: '
assignees:
  - Fyoncle
labels:
  - bug
body:
  - type: checkboxes
    id: importantsteps
    attributes:
      label: Important Steps
      description: The steps you have to complete before opening a issue.
      options:
        - label: >-
            I have checked that theres no other similar issue opened about this
            bug.
          required: true
        - label: >-
            I have checked the Known Issues & Fixes on the Wiki and my issue is not stated there.
          required: true
  - type: input
    id: modpackversion
    attributes:
      label: Modpack Version
      description: Which Elysium Days version you using?
      placeholder: 3.5.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear explanation of the issue.
      placeholder: My game crashes when trying to create a world.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the issue you're experiencing.
      placeholder: |
        1. Install Latest Elysium Days
        2. Join A World
        3. Click the X block
        4. See the crash
  - type: input
    id: logs
    attributes:
      label: Log File
      description: >
        Please upload the logs to the [mclo.gs](https://mclo.gs/) website, not as
        text.
      placeholder: 'https://mclo.gs/.....'
