name: Bug report
about: Create a report to help us improve
title: '[Bug]: '
labels: 
- bug
assignees:
- Fyoncle

- [ ] I have checked that theres no other similar issue opened about this bug.
- [ ] I have checked the [Known Issues](https://github.com/Fyoncle/Elysium-Days/wiki/Known-Issues-&-Fixes) Wiki and my issue is not there.

- type: input
    id: minecraft
    attributes:
      label: Modpack Version
      description: Which Elysium Days version you using?
      placeholder: 3.5.0
    validations:
      required: true

**Describe the bug**
Explanation of what is the bug about.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
